config/routes.rb
Stagebeheer::Application.routes.draw do
  resources :companies
  root :to => redirect('/companies')
  get '/companies/sort/:sortarg', to: 'companies#index'
  resources :stagiairs

end

app/models/company.rb
class Company < ActiveRecord::Base
	attr_accessible :name,:adress, :zip, :city, :applicatie, :beheer, :netwerk, :ecabo, :activity, :email, :comment
	def self.all_selections ; [:applicatie, :beheer, :netwerk, :blanco] ; end #  shortcut: array of strings
	def self.no_type
		find(:all, 	
    		:conditions => ['applicatie is ? AND beheer is ? AND netwerk is  ?' , nil, nil, nil])
	end
end

app/models/stagiair.rb
class Stagiair < ActiveRecord::Base
	attr_accessible :name,:surname, :nova_id, :group
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
#  	debugger
  	@all_selections=Company.all_selections
  	if !params[:sortarg].nil?
			@sortarg = params[:sortarg]
			session[:sortarg] = @sortarg
#		@fromsess = false
		else
			@sortarg = session[:sortarg]
#		@fromsess= true
		end
  	@companies =  Company.order(@sortarg)
  	@name_class = (@sortarg == "name" ? "hilite" : nil)
		@city_class = (@sortarg == "city" ? "hilite" : nil)
		@appCheck = true
		@selected = Hash.new
	if !params["selections"].nil? 
		@selected = params["selections"]
		session[:selections]= params["selections"]
		@fromsess ||= false
	else 
		@selected = session[:selections]
		@fromsess ||= true
	end
	if @selected == nil

		@full_selected = @all_selections.collect { |v| [v,1]} 
		@selected =Hash[@full_selected]
	end

	if  params[:id] == nil
				@companies = []
				@selected.each do |s|
		#debugger
					if s[0].to_s == "blanco"
				
						Company.no_type.each do |c|
							@companies << c
						end	
					else

						Company.where(s[0] => :true).each do |record|
							@companies << record
						end
					end

	end

	if params[:ecabo] == nil ; params[:ecabo] = "all" ; end
#		debugger
	if !(params[:ecabo] == "all")
		if params[:ecabo] == "nee"
			@companies.reject!{ |c| c.ecabo}
		else
			@companies.reject!{ |c| !c.ecabo}
		end
	end

				
#debugger
	  @companies = @companies.uniq.sort_by { |hsh| hsh[@sortarg] }
	  
		@full_selected = @all_selections.collect { |v| [v,1] }
		#@selected = Hash[@full_selected]

	end	
	#debugger
  end
  def show
    id = params[:id] # retrieve company ID from URI route
    @company = Company.find(id) # look up company by unique ID
    #debugger
    render(:partial => 'company', :object => @company) if request.xhr?
    # will render app/views/companies/show.<extension> by default
  end
	def new
		# default: render 'new'  template
	end
	def create
		@company = Company.new(params[:company])
		if @company.save
			flash[:notice]= "#{@company.name} aangemaakt."
			redirect_to companies_path
		else
			render 'new' # 'new'  template can access @company field values
		end
	end
	def edit
		@company = Company.find params[:id]
	end
	def update
		@company = Company.find params[:id]
		if @company.update_attributes(params[:company])
			flash[:notice] = "Bedrijfsinfo voor #{@company.name} gewijzigd."
			redirect_to companies_path
		else
			render 'edit' # 'edit' template can access @company field values
		end
	end
	def destroy
		@company =  Company.find(params[:id])
		@company.destroy
		flash[:notice] = "Bedrijf '#{@company.name}' verwijderd."
		redirect_to companies_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_company.html.haml
-#debugger
- # Single row of all companies table
%tr
  %td=company.name
  %td=company.city
  %td= check_box_tag "#{company.applicatie}", 1, company.applicatie, disabled: true
  %td= check_box_tag "#{company.beheer}", 1, company.beheer, disabled: true
  %td= check_box_tag "#{company.netwerk}", 1, company.netwerk, disabled: true
  %td= check_box_tag "#{company.ecabo}", 1, company.ecabo, disabled: true
  %td= link_to "Details voor #{company.name}", company_path(company),  class: 'btn btn-primary btn-xs'
  %td= link_to "Wijzig info" , edit_company_path(company), class: 'btn btn-info btn-xs' 
  %td= link_to "Verwijder Bedrijf" , company_path(company), class: 'btn btn-danger btn-xs', :method => :delete ,data: {confirm: "Are you sure? "}

app/views/companies/_company_form.html.haml
-# this is the partial

- unless !@company || @company.errors.empty?
	#warning
		Errors prevented this company from being #{controller.action_name}d:
		%ul
			- @company.errors.full_messages.each do |error|
				%li= error

= label :company, :name, 'Naam'
= text_field :company, :name 
	
= label :company, :adress, 'Adres'
= text_field :company, :adress 

= label :company, :zip, 'Postcode'
= text_field :company, :zip 

= label :company, :city, 'Woonplaats'
= text_field :company, :city 

= label :company, :abn, 'ABN'
= text_field :company, :abn 

= label :company, :ecabo, 'Ecabo'
= text_field :company, :ecabo 

= label :company, :activity, 'Activiteit'
= text_field :company, :activity 

= label :company, :email, 'Email'
= text_field :company, :email 

= label :company, :comment, 'Opmerkingen'
= text_field :company, :comment 

app/views/companies/edit.html.haml
-# This file is in app/views/movies/edit.html.haml

%h2 Wijzigen Bedrijfsinfo

= form_tag company_path(@company), :method => :put do

	= render :partial => 'company_form'
	
	= submit_tag 'Wijzigingen Opslaan'
	
-#= link_to "Back to movie list", movies_path

app/views/companies/index.html.haml
-# This file is in app/views/companies/index.html.haml

%p{:class => 'text-center'} 
  aantal bedrijven :
  = @companies.count
  = link_to "Bedrijf toevoegen" , new_company_path, class: 'btn btn-primary btn-xs' 
= form_tag companies_path, :id => "selections_form", :method => :get do
  %div{:class => 'bluebox bg-info pull-left'} 
    Inclusief:
    - @all_selections.each do |selection|
      = selection
      -if @selected.has_key?(selection) == true
        = check_box_tag "selections[#{selection}]",1,true, :id => selection.to_s
      -else
        = check_box_tag "selections[#{selection}]", :id => selection.to_s
  -#debugger
  
  %div{:class => 'ecabox bg-warning pull-left'} 
    Ecabo:
    all
    = radio_button_tag "ecabo", "all", (params[:ecabo] == "all"), :class=> 'ecabox'
    ja 
    = radio_button_tag "ecabo", "ja", (params[:ecabo] == "ja"), :class=> 'ecabox'
    nee
    = radio_button_tag "ecabo", "nee", (params[:ecabo] == "nee" ), :class=> 'ecabox'
    
  = submit_tag 'Refresh', :id => "selections_submit"
    

  
%table{:class => 'table-class table-condensed table-bordered table-striped table-responsive'}
  %thead
    %tr 
      %th{:class => @name_class}= link_to "Naam", companies_path()+"/sort/name", :id => "name_header"
      %th{:class => @city_class}= link_to "Woonplaats", companies_path()+"/sort/city", :id => "city_header"
      
      %th App
      %th Beh
      %th Net
      %th Ecabo
  %tbody
    -#debugger
    =render :partial=>'company', :collection=>@companies

app/views/companies/new.html.haml
-# This file is in app/views/movies/new.html.haml
%h2 Create New Company

= form_tag companies_path, :method => :post do

	= render :partial => 'company_form'
	
	= submit_tag 'Save Changes'
	
-#= link_to "Back to movie list", movies_path

app/views/companies/show.html.haml
-# THis file is in app/views/companys/show.html.haml
%h2 Details voor #{@company.name}

%ul#details
	%li
		Naam:
		= @company.name
	%li
		Adres:
		= @company.adress
	%li 
		Woonplaats: 
		= @company.city
	%li 
		Activiteit: 
		= @company.activity	
	%li 
		Abn: 
		= @company.abn	
	%li 
		Ecabo: 
		= @company.ecabo	
	%li 
		email: 
		= @company.email
	%li 
		Opmerkingen: 
		= @company.comment						

= link_to "Wijzigen Bedrijfsinfo" , edit_company_path(@company)
|

%td= link_to "Verwijder Bedrijf" , company_path(@company), class: 'btn btn-danger btn-xs', :method => :delete ,data: {confirm: "Weet u het zeker? "}
|
= link_to "Terug naar Bedrijvenlijst", companies_path
|

app/views/layouts/application.html.haml
!!! 5
%html

	%head
		%title Stagebeheer
		= stylesheet_link_tag 'application'
		= stylesheet_link_tag 'custom'
		= csrf_meta_tags

	%body
		%h2{:class => 'text-uppercase text-center'} Stages bij ICT Academie Haarlem
		- if flash[:notice]
			#notice.message= flash[:notice]
		- elsif flash[:warning]
			#warning.message= flash[:warning]
		=yield